version: "3.8"

services:
  auth:
    container_name: auth
    image: "connextproject/nats-auth"
    environment:
      VECTOR_JWT_SIGNER_PUBLIC_KEY_PATH: "/pub.key"
      VECTOR_JWT_SIGNER_PRIVATE_KEY_PATH: "/priv.key"
      VECTOR_NATS_URL: "nats://nats:4222"
      VECTOR_ADMIN_TOKEN: "connext1234"
      VECTOR_PORT: "5040"
      VECTOR_PROD: "true"
    ports:
      - "5040:5040"
    volumes:
      - "./config/messaging/pub.key:/pub.key"
      - "./config/messaging/priv.key:/priv.key"
    networks:
      - nxtp
    depends_on:
      - nats

  nats:
    container_name: nats
    image: "connextproject/vector_nats"
    environment:
      JWT_SIGNER_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwQYLqNYRZrZcbD7Dx82b
        rIiuOt2XSBI6oAYPb8WcnX1me4UyfVsx7eIF+DnyOJ7sinaG6hwx7zuyUPGy0QkI
        YycNp2XX9BhA7zkWkrkIUAy9N/2Onq/HGXmaCGQQ6MMlopaz6ryuKmatCcWHUbBW
        R/y2I79kK7IulWAJoX0yt867MToj8bEwlc8BIzqsWV+IwiXps5nX5PUHk/nwWMXI
        JYYTE2VpJhwrkuw2R2VuaHxYoNneDlgNN/EJtZuqrAheqNBcd+Jyujpo4uaieIGC
        tBdYy9hoxaBYhR82SGClFoRGWD4cb/3GTYXJf7ZaZrg/zkqEvrks6FNsFPeCslYM
        A/jlFQNkoVUSn15n1B7ndetebEIRtFkaVQ89Ejxr3oHGdG2i6OAnuEQpAUOsG9Fu
        sHv61RMCo+CcWwT1yMACcxWfN/aL9dOE+zDtQXSM1P5wYOHBaCHOnyCaumyieZ7v
        sxGKQmfS/PtUWZTpHHdsafaVpUxkq0YFx5VzFbqraQf3AFU1wRaJYm6JNdHCLpVg
        XBYYKUz9kGFJMe0T21AUeV53gi1yUwy6+jJQJbdV9bCtZnUQi7YlWmIrE25ABs2O
        DvKsD63QcBOW4TATrd6+zUX3n80ZGz/60oS4SPOBmlGjdoZD9bASYCNrqJTBSegA
        /jwvk787srHfu0XqjeY3DAkCAwEAAQ==
        -----END PUBLIC KEY-----"
    ports:
      - "4222:4222"
      - "4221:4221"
    networks:
      - nxtp

  ################################################################################

  router:
    container_name: router
    image: ghcr.io/connext/nxtp-router:$ROUTER_VERSION
    restart: always
    ports:
      - $ROUTER_EXTERNAL_PORT:8080
    volumes:
      - ./config.json:/home/node/router/config.json
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - nxtp
    depends_on:
      - auth

  ################################################################################

  logdna:
    container_name: logdna
    image: logdna/logspout:v1.2.0
    restart: always
    environment:
      LOGDNA_KEY: $LOGDNA_KEY
      TAGS: $LOGDNA_TAG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - nxtp

  ################################################################################

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=45d
    volumes:
      - ./data/prometheusConfig/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheusConfig/alert.rules.host:/etc/prometheus/alert.rules.host
      - ./data/prometheusConfig/alert.rules.prod:/etc/prometheus/alert.rules.prod
      # - ./data/prometheusConfig/alert.rules.router:/etc/prometheus/alert.rules.router
      - prometheus:/prometheus
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - nxtp

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - $GRAFANA_EXTERNAL_PORT:3000
    volumes:
      - ./data/grafanaConfig/grafana:/etc/grafana
      - ./data/grafanaConfig/dashboards:/etc/dashboards
      - grafana:/var/lib/grafana
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - nxtp

  #  alertmanager-discord:
  #    container_name: alertmanager-discord
  #    image: benjojo/alertmanager-discord
  #    restart: always
  #    environment:
  #      DISCORD_WEBHOOK: $DISCORD_WEBHOOK
  #    logging:
  #      driver: json-file
  #      options:
  #          max-size: 10m
  #    networks:
  #      - nxtp

  ################################################################################

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.1.2
    restart: always
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns)(/)
    cap_add:
      - SYS_TIME
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - nxtp

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.39.0
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - nxtp

################################################################################

networks:
  nxtp:

volumes:
  prometheus:
  grafana:
